name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
            executable: fixen-lsp

          - os: macos-13
            target: darwin-x64
            executable: fixen-lsp

          - os: macos-latest
            target: darwin-arm64
            executable: fixen-lsp

          - os: windows-latest
            target: win32-x64
            executable: fixen-lsp.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout fixen-lsp
        uses: actions/checkout@v4
        with:
          path: fixen-lsp

      - name: Checkout fixen
        uses: actions/checkout@v4
        with:
          repository: SKCheongBrian/fixen
          ref: feat/name_fields
          path: fixen

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.12.2"
          cabal-version: "3.16.0.0"

      - name: Cabal update
        working-directory: fixen-lsp
        run: cabal update

      - name: Build
        working-directory: fixen-lsp
        run: cabal build

      - name: Find executable
        id: binary
        working-directory: fixen-lsp
        shell: bash
        run: |
          echo "path=$(cabal list-bin fixen-lsp)" >> "$GITHUB_OUTPUT"

      - name: Copy executable
        shell: bash
        run: |
          mkdir -p dist
          cp "${{ steps.binary.outputs.path }}" \
             "dist/${{ matrix.executable }}"

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: fixen-lsp-${{ matrix.target }}
          path: dist/${{ matrix.executable }}
